baseURL = "https://giou-k.github.io/"
languageCode = 'en-us'
title = 'My New Hugo Site'


theme = "loficode"

[params]
author = "Konstantinos Georgiou"
description = "Write to Remember"

# Profile section
[params.profile]
name = "Konstantinos Georgiou"
tagline = "Write to Remember"
photo = "/images/profile.png"

# Social links - Supported platforms: github, twitter, linkedin, email, mastodon, youtube, instagram, facebook
[params.social]
github = "giou-k"
twitter = ""
linkedin = "your-linkedin-username"
# email = "your-email@example.com"
# mastodon = "https://mastodon.social/@yourusername"
# youtube = "https://youtube.com/@yourusername"
# instagram = "your-instagram-username"
# facebook = "your-facebook-username"

# Navigation menu
[[menu.main]]
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 20

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 30
